param(
  [Parameter(Mandatory = $false)]
  [string]$SourceDir = "E:\官方文件\client-extra",

  [Parameter(Mandatory = $false)]
  [string]$TemplateHtml = "guides\ch1-sec2-read-official-code.html",

  [Parameter(Mandatory = $false)]
  [string]$OutHtml = "guides\ch1-sec2-read-official-code.local.html",

  [Parameter(Mandatory = $false)]
  [int]$MaxFiles = 60
)

$ErrorActionPreference = "Stop"

function To-ForwardSlashes([string]$path) {
  return ($path -replace "\\", "/")
}

function Escape-ScriptEnd([string]$text) {
  return ($text -replace "</script>", "<\/script>")
}

function Read-TextFileRaw([string]$path) {
  try {
    return Get-Content -LiteralPath $path -Raw -Encoding UTF8
  } catch {
    return Get-Content -LiteralPath $path -Raw
  }
}

if (!(Test-Path -LiteralPath $SourceDir)) {
  throw "SourceDir not found: $SourceDir"
}

if (!(Test-Path -LiteralPath $TemplateHtml)) {
  throw "TemplateHtml not found: $TemplateHtml"
}

$template = Get-Content -LiteralPath $TemplateHtml -Raw -Encoding UTF8

$startMarker = "<!-- OFFICIAL_VIEWER_TEMPLATES_START -->"
$endMarker = "<!-- OFFICIAL_VIEWER_TEMPLATES_END -->"

$startIndex = $template.IndexOf($startMarker)
$endIndex = $template.IndexOf($endMarker)
if ($startIndex -lt 0 -or $endIndex -lt 0 -or $endIndex -le $startIndex) {
  throw "Markers not found or invalid in template: $TemplateHtml"
}

$selected = New-Object System.Collections.Generic.List[string]

# Curated list (best for learning modding resources). Add if exists.
$curated = @(
  "version.json",
  "pack.mcmeta",
  "assets\minecraft\lang\zh_cn.json",
  "assets\minecraft\lang\en_us.json",
  "assets\minecraft\texts\credits.json",
  "data\minecraft\worldgen\noise_settings\overworld.json",
  "data\minecraft\worldgen\noise_settings\amplified.json",
  "data\minecraft\worldgen\noise_settings\large_biomes.json"
)

foreach ($rel in $curated) {
  $full = Join-Path $SourceDir $rel
  if (Test-Path -LiteralPath $full) {
    $selected.Add($full) | Out-Null
  }
}

# Fill remaining slots with small text files (json/shader/meta) from the folder.
$textExt = @(".json", ".mcmeta", ".txt", ".fsh", ".vsh", ".glsl", ".mf", ".sf")
$allTextFiles = Get-ChildItem -LiteralPath $SourceDir -Recurse -File -Force |
  Where-Object { $textExt -contains $_.Extension.ToLowerInvariant() } |
  Sort-Object Length, FullName

foreach ($f in $allTextFiles) {
  if ($selected.Count -ge $MaxFiles) { break }
  if ($selected.Contains($f.FullName)) { continue }
  $selected.Add($f.FullName) | Out-Null
}

if ($selected.Count -eq 0) {
  throw "No eligible text files found under: $SourceDir"
}

$blocks = New-Object System.Text.StringBuilder
$blocks.AppendLine($startMarker) | Out-Null
$blocks.AppendLine("<!-- generated by scripts/generate-client-extra-local.ps1 ; do not commit to public repo -->") | Out-Null

foreach ($fullPath in $selected) {
  $relPath = $fullPath.Substring($SourceDir.TrimEnd('\').Length).TrimStart('\')
  $dataFile = To-ForwardSlashes $relPath
  $raw = Read-TextFileRaw $fullPath
  $raw = $raw -replace "\r\n", "`n"
  $raw = Escape-ScriptEnd $raw
  $blocks.Append("<script type=""text/plain"" data-file=""") | Out-Null
  $blocks.Append($dataFile) | Out-Null
  $blocks.Append(""">") | Out-Null
  $blocks.Append($raw.TrimEnd()) | Out-Null
  $blocks.AppendLine("</script>") | Out-Null
}

$blocks.AppendLine($endMarker) | Out-Null

$before = $template.Substring(0, $startIndex)
$after = $template.Substring($endIndex + $endMarker.Length)
$out = $before + $blocks.ToString() + $after

Set-Content -LiteralPath $OutHtml -Value $out -Encoding UTF8
Write-Host "Generated: $OutHtml"
Write-Host "Files embedded: $($selected.Count)"
